# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.6.0
      with:
        # Path to the local folder you want to copy.
        local: ''
        # Path on the remote server to copy to.
        remote: ${{ secrets.REMOTE_TARGET }}
        # Hostname or IP address of the server.
        host: ${{ secrets.REMOTE_HOST }}
        # Username for authentication.
        username: ${{ secrets.REMOTE_USER }}
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        privateKey: ${{ secrets.SERVER_SSH_KEY }}

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        # Command to execute on the remote server.
        command: ./update.sh
        # Hostname or IP address of the server.
        host: ${{ secrets.REMOTE_HOST }}
        # Username for authentication.
        username: ${{ secrets.REMOTE_USER }}
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        privateKey: ${{ secrets.SERVER_SSH_KEY }}

